apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: aziz77/garage-front:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 31001
